config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users do
    resources :shelves
    resources :shelved_books, only: [:create, :destroy]
  end

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :author, presence: true
  validates :description, presence: true
  validates :page_count, presence: true
  validates :release_year, presence: true
  validates :title, presence: true, uniqueness: {case_sensitive: false}

  has_many :shelved_books
end

app/models/book_search.rb
class BookSearch
  def initialize(query)
    @query = query
  end

  def call
    if @query
      Book.where('lower(title) LIKE ? OR lower(author) LIKE ? OR lower(description) LIKE ?',
                 "%#{@query.downcase}%", "%#{@query.downcase}%", "%#{@query.downcase}%")
    else
      Book.all
    end
  end
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  has_many :shelved_books
  has_many :books, through: :shelved_books
end

app/models/shelved_book.rb
class ShelvedBook < ApplicationRecord
  belongs_to :shelf
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shelves

  has_secure_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    respond_to do |format|
      format.html do
        # Delegate to Devise's #current_user
        super
      end

      format.json do
        @current_user ||= User.find_by(token: request.headers["Authorization"])
      end
    end
  end

  def require_authentication
    return if current_user
    respond_to do |format|
      format.html do
        flash[:alert] = "You must be signed in to do that"
        redirect_to root_path
      end
      format.json do
        head :unauthorized
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_authentication, except: [:index, :show]

  def index
    @books = BookSearch.new(params[:query]).call
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      format.html do
        if(@book.save)
          flash[:notice] = "Book added successfully"
          redirect_to book_path(@book)
        else
          flash[:alert] = "Book was not saved"
          render 'new'
        end
      end

      format.json do
        if(@book.save)
          render @book
        else
          errors = { errors: @book.errors }
          render json: errors, status: :unprocessable_entity
        end
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html do
        if update_book
          flash[:notice] = 'Book was successfully updated'
          redirect_to book_path(@book)
        else
          flash[:alert] = "Book was not saved"
          render 'edit'
        end
      end

      format.json do
        if update_book
          render @book
        else
          errors = { errors: @book.errors }
          render json: errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html do
        flash[:notice] = 'Book was successfully deleted'
        redirect_to root_path
      end

      format.json do
        head :ok
      end
    end
  end

  private

  def update_book
    @book.update(book_params)
  end

  def book_params
    params.require(:book).permit(:title, :page_count, :release_year, :description, :author, :query)
  end
end

app/controllers/concerns/shelf_authorization.rb
module ShelfAuthorization
  extend ActiveSupport::Concern

  def can_manage_shelf?(shelf)
    if current_user == shelf.user
      true
    else
      authorization_redirect
      false
    end
  end

  def authorization_redirect
    flash[:alert] = "You don't have permission to manage this shelf"
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shelved_books_controller.rb
class ShelvedBooksController < ApplicationController
  include ShelfAuthorization

  before_action :require_authentication

  def create
    shelf = Shelf.find(shelved_book_params[:shelf_id])
    book = Book.find(shelved_book_params[:book_id])

    return unless can_manage_shelf?(shelf)
    ShelvedBook.create(shelf: shelf, book: book)

    flash[:notice] = "Book successfully added to #{shelf.title} shelf"
    redirect_to book_path(book)
  end

  def destroy
    @shelved_book = ShelvedBook.find_by(id: params[:id])
    return unless can_manage_shelf?(@shelved_book.shelf)
    @shelved_book.destroy
    flash[:notice] = 'Book was successfully removed'
    redirect_to user_shelf_path(current_user, @shelved_book.shelf)
  end

  private

  def shelved_book_params
    params.require(:shelved_book).permit(:book_id, :shelf_id)
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  include ShelfAuthorization

  before_action :require_authentication

  def new
    @shelf = Shelf.new
  end

  def show
    @shelf = Shelf.find(params[:id])
    @shelved_books = @shelf.shelved_books.includes(:book)
  end

  def index
    @user = User.find(params[:user_id])
    @shelves = @user.shelves
  end

  def create
    @shelf = current_user.shelves.new(shelf_params)

    if @shelf.save
      flash[:notice] = "Shelf added successfully"
      redirect_to user_shelf_path(current_user, @shelf)
    else
      flash[:alert] = "Shelf was not saved"
      render 'new'
    end
  end

  def edit
    @shelf = Shelf.find(params[:id])
    return unless can_manage_shelf?(@shelf)
  end

  def update
    @shelf = Shelf.find(params[:id])
    return unless can_manage_shelf?(@shelf)
    if @shelf.update(shelf_params)
      flash[:notice] = "Shelf was successfully updated"
      redirect_to user_shelf_path(current_user, @shelf)
    else
      flash[:alert] = "Shelf could not be updated"
      render 'edit'
    end
  end

  private

  def shelf_params
    params.require(:shelf).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def available_shelves_for(book)
    shelves = current_user.shelves
    shelves = shelves.reject do |shelf|
      shelf.books.include?(book)
    end
    options_from_collection_for_select(shelves, :id, :title)
  end
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <ul>
      <% @book.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :release_year, "Year of release" %>
  <%= f.text_field :release_year %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :page_count, "Number of pages" %>
  <%= f.text_field :page_count %>

  <%= f.submit "Save" %>
<% end %>

app/views/books/_list.html.erb
<% if @books.any? %>
  <table>
    <%= render partial: "books/list_table_header" %>

    <tbody>
    <% @books.each do |book| %>
      <tr>
        <%= render partial: "books/list_table_row", locals: { book: book } %>
      </tr>
    <% end%>
    </tbody>
  </table>
<% end %>

app/views/books/_list_table_header.html.erb
<thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Year of release</th>
    <th>Action</th>
  </tr>
</thead>

app/views/books/_list_table_row.html.erb
  <td><%= link_to book.title, book %></td>
  <td><%= book.author %></td>
  <td><%= book.release_year %></td>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= form_tag(books_path, method: :get) do %>
  <%= text_field_tag 'query'  %>
  <%= submit_tag "Search" %>
<% end %>

<% if @books %>
  <span><%= pluralize(@books.count, 'book') %> found</span>
<% end %>

<%= render 'books/list' %>

app/views/books/new.html.erb
<h1>Add a new book</h1>

<%= render "form"%>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<% if current_user %>
  <%= link_to "Edit book", edit_book_path %>
  <%= link_to "Delete book", book_path, method: :delete %>
<% end %>

<% if current_user %>
  <h2>Add to shelf</h2>

  <% if available_shelves_for(@book).size > 0 %>
    <%= form_for [current_user, ShelvedBook.new] do |f| %>
      <%= f.label :shelf_id, "My shelves" %>
      <%= f.select :shelf_id, available_shelves_for(@book) %>
      <%= f.hidden_field :book_id, value: @book.id %>
      <%= f.submit "Add to shelf" %>
    <% end %>
  <% else %>
    You have no available shelves
  <% end %>
<% end %>
<p>by <%= @book.author %></p>
<p><%= @book.description %></p>
<small>
  <span>Published in <%= @book.release_year %> / <%= @book.page_count %> pages</span>
</small>

app/views/home/index.html.erb
<%= link_to "View all books", books_path %>

<% if !user_signed_in? %>
  <%= link_to "Sign up", new_user_registration_path  %>
  <%= link_to "Sign in", new_user_session_path %>
<% else %>  
  <%= link_to "Add a book", new_book_path %> 
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <%= link_to "Add a shelf", new_user_shelf_path(current_user) %>
  <%= link_to "My shelves", user_shelves_path(current_user) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookworm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shelves/edit.html.erb
<h1>Edit shelf</h1>
<%= form_for [current_user, @shelf] do |f| %>
  <% if @shelf.errors.any? %>
    <ul>
      <% @shelf.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Save" %>
<% end %>

app/views/shelves/index.html.erb
<h1>
  <% if current_user == @user %> 
    My
  <% else %>
    <%= @user.email %>'s
  <% end %>
  shelves
</h1>

<% if @shelves.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
    </tr>
    </thead>
    <tbody>
  <% @shelves.each do |shelf| %>
    <tr>
      <td><%= link_to shelf.title, user_shelf_path(shelf.user, shelf) %></td>
    </tr>
  <% end%>
    </tbody>
  </table>
<% end %>

app/views/shelves/new.html.erb
<h1>Add a new shelf</h1>
<%= form_for [current_user, @shelf] do |f| %>
  <% if @shelf.errors.any? %>
    <ul>
      <% @shelf.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Save" %>
<% end %>

app/views/shelves/show.html.erb
<h1><%= @shelf.title %> Shelf</h1>
<%= link_to "Edit shelf", edit_user_shelf_path(current_user, @shelf) %>

<% if @shelved_books.any? %>
  <table>
    <%= render partial: "books/list_table_header" %>

    <tbody>
    <% @shelved_books.each do |shelved_book| %>
      <% book = shelved_book.book %>

      <tr>
        <%= render partial: "books/list_table_row", locals: { book: book } %>
        <td><%= link_to "Remove", user_shelved_book_path(@shelf.user, shelved_book), method: :delete, data: { action: "remove" } %></td>
      </tr>
    <% end%>
    </tbody>
  </table>
<% end %>